module.exports = [
  {
    id: 1,
    scientific_name: "Malus Domestica",
    tree_name: "Manzano",
    fruit_name: "Manzana",
    family: "Rosáceas",
    origin: "",
    description: "La manzana es el fruto del manzano, árbol de la familia de las rosáceas, tiene piel o cáscara color rojo brillante, pulpa blanquecina, es algo arenosa y con un sabor algo ácido, de esta variedad procede la variedad Royal Red Delicious.",
    bloom: "Primavera",
    harvest_time: "",
    life_cycle: "60-80 años",
    climatic_zone: "Frio",
    // producing_countries: []
  },
  {
    id: 2,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Banana",
    family: "",
    origin: "",
    description: "",
    bloom: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 3,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Pera",
    family: "",
    origin: "",
    description: "",
    bloom: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 4,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Limón",
    family: "Cítrico",
    origin: "",
    description: "",
    bloom: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 5,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Mandarina",
    family: "Cítrico",
    origin: "",
    description: "",
    bloom: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 6,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Naranja",
    family: "Cítrico",
    origin: "",
    description: "",
    bloom: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 7,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Pomelo",
    family: "Cítrico",
    origin: "",
    description: "",
    bloom: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 8,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Damasco",
    family: "Cítrico",
    origin: "",
    description: "",
    bloom: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 9,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Ciruela",
    family: "",
    origin: "",
    description: "",
    bloom: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 10,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Durazno",
    family: "",
    origin: "",
    description: "",
    bloom: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  }
];