// Fuente de datos: Wikipedia.
module.exports = [
  {
    id: 1,
    scientific_name: "Malus Domestica",
    tree_name: "Manzano",
    fruit_name: "Manzana",
    family: "Rosáceas",
    origin: "Asia Central",
    description: "La manzana es el fruto del manzano, árbol de la familia de las rosáceas. Es una fruta pomácea de forma redonda y sabor más o menos dulce, dependiendo de la variedad. La manzana es un árbol caducifolio, generalmente de 2 a 4,5 m (6 a 15 pies) de altura en cultivo y hasta 9 m (30 pies) en la naturaleza.",
    bloom: "Primavera",
    maturation_fruit: "Finales del verano o otoño",
    life_cycle: "60-80 años",
    climatic_zone: "Frio",
    // producing_countries: []
  },
  {
    id: 2,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Banana",
    family: "",
    origin: "",
    description: "",
    bloom: "",
    maturation_fruit: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 3,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Pera",
    family: "",
    origin: "",
    description: "",
    bloom: "",
    maturation_fruit: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 4,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Limón",
    family: "Cítrico",
    origin: "",
    description: "",
    bloom: "",
    maturation_fruit: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 5,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Mandarina",
    family: "Cítrico",
    origin: "",
    description: "",
    bloom: "",
    maturation_fruit: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 6,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Naranja",
    family: "Cítrico",
    origin: "",
    description: "",
    bloom: "",
    maturation_fruit: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 7,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Pomelo",
    family: "Cítrico",
    origin: "",
    description: "",
    bloom: "",
    maturation_fruit: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 8,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Damasco",
    family: "Cítrico",
    origin: "",
    description: "",
    bloom: "",
    maturation_fruit: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 9,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Ciruela",
    family: "",
    origin: "",
    description: "",
    bloom: "",
    maturation_fruit: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 10,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Durazno",
    family: "",
    origin: "",
    description: "",
    bloom: "",
    maturation_fruit: "",
    life_cycle: "",
    climatic_zone: "",
  }
];