module.exports = [
  {
    id: 1,
    scientific_name: "Malus Domestica",
    tree_name: "Manzano",
    fruit_name: "Manzana",
    family: "Rosáceas",
    description: "",
    origin: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
    // producing_countries: []
  },
  {
    id: 2,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Banana",
    family: "",
    description: "",
    origin: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 3,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Pera",
    family: "",
    description: "",
    origin: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 4,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Limón",
    family: "Cítrico",
    description: "",
    origin: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 5,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Mandarina",
    family: "Cítrico",
    description: "",
    origin: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 6,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Naranja",
    family: "Cítrico",
    description: "",
    origin: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 7,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Pomelo",
    family: "Cítrico",
    description: "",
    origin: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 8,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Damasco",
    family: "Cítrico",
    description: "",
    origin: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 9,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Ciruela",
    family: "",
    description: "",
    origin: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  },
  {
    id: 10,
    scientific_name: "",
    tree_name: "",
    fruit_name: "Durazno",
    family: "",
    description: "",
    origin: "",
    harvest_time: "",
    life_cycle: "",
    climatic_zone: "",
  }
];